// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteAppBackend;

#nullable disable

namespace NoteAppBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240126201527_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NoteAppBackend.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("NoteAppBackend.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("NoteAppBackend.Entities.NoteCategory", b =>
                {
                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<int>("IdNote")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("NoteId")
                        .HasColumnType("int");

                    b.HasKey("IdCategory", "IdNote");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NoteId");

                    b.ToTable("NoteCategories");
                });

            modelBuilder.Entity("NoteAppBackend.Entities.NoteCategory", b =>
                {
                    b.HasOne("NoteAppBackend.Entities.Category", "Category")
                        .WithMany("Notecategories")
                        .HasForeignKey("CategoryId");

                    b.HasOne("NoteAppBackend.Entities.Note", "Note")
                        .WithMany("Notecategories")
                        .HasForeignKey("NoteId");

                    b.Navigation("Category");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("NoteAppBackend.Entities.Category", b =>
                {
                    b.Navigation("Notecategories");
                });

            modelBuilder.Entity("NoteAppBackend.Entities.Note", b =>
                {
                    b.Navigation("Notecategories");
                });
#pragma warning restore 612, 618
        }
    }
}
